name: basicaudio
channels:
dependencies:
  - python
  - tensorboard
  - ffmpeg
  - pip:
    - aiohttp
    - Brotli
    - datasets
    - fqdn
    - importlib_metadata
    - ipdb
    - isoduration
    - jsonpointer
    - jupyter
    - librosa
    - natsort
    - openpyxl
    - pip
    - PySocks
    - seaborn
    - tensorboard
    - tinycss2
    - torchaudio
    - torchcodec
    - torchvision
    - transformers
    - uri-template
    - webcolors
    - wheel
